name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Download resources
      run: |
        sudo apt update
        sudo apt-get upgrade
        git clone https://github.com/sebaubuntu-python/dumpyara.git
        cd dumpyara
        ls
        pip3 install .
        git clone https://github.com/sebaubuntu-python/aospdtgen.git
        cd aospdtgen
        pip install -r requirements.txt
        pip install .
        python3 -m aospdtgen -h
        curl -o ota.zip https://gauss-componentotacostmanual-in.allawnofs.com/remove-8c0f8b26e3321a05060a6b2ab2d632ea/component-ota/22/10/19/c31025c3a26445a6810d295fa01cca67.zip
        ls
        python3 -m dumpyara ota.zip
        python3 -m -o /aospdt aospdtgen /
        ls
        rm -f ota.zip
        cd aospdt
        git add .
        
    - name: Push new files to GitHub
      run: |
        git config --global user.email "indiamadhuraj@gmail.com"
        git config --global user.name "madhuraj0"
        git commit -m "build commit"
        git push https://${GITHUB_ACTOR}:${{ secrets.PAT }}@github.com/${{ github.repository }}.git main --force
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        PAT: ${{ secrets.PAT }}
