name: Build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install CPIO and python
      run: |
        sudo apt install cpio
        pip3 install twrpdtgen
        git clone https://github.com/twrpdtgen/twrpdtgen.git
        wget  -c https://files.catbox.moe/k2kktd.img -o boot.img
        ls
        python3 -m twrpdtgen boot.img
        git add .
        
    - name: Push new files to GitHub
      run: |
        git config --global user.email "indiamadhuraj@gmail.com"
        git config --global user.name "madhuraj0"
        git commit -m "build commit"
        git push https://${GITHUB_ACTOR}:${{ secrets.PAT }}@github.com/${{ github.repository }}.git main --force
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        PAT: ${{ secrets.PAT }}
