name: Build LineageOS Recovery for MTK device
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to build'
        required: true

env:
  DEVICE_TREE: ${{ github.workspace }}/device/oplus/RE879EL1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y bc bison build-essential curl flex g++-multilib gcc-multilib git gnupg gperf htop imagemagick lib32ncurses5-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-gtk3-dev libxml2 libxml2-utils lzop maven openjdk-8-jdk pngcrush pngquant python3 python3-dev python3-pip repo rsync schedtool squashfs-tools unzip wput xsltproc zip zlib1g-dev

    - name: Clone LineageOS Source
      uses: actions/checkout@v2

    - name: Install Repo
      run: |
        curl https://storage.googleapis.com/git-repo-downloads/repo > /usr/local/bin/repo
        chmod a+x /usr/local/bin/repo
        export PATH=/usr/local/bin:$PATH

    - name: Initialize Build Environment
      run: |
        cd ${{ github.workspace }}
        repo init -u git://github.com/LineageOS/android.git -b ${{ github.event.inputs.branch }}
        repo sync -j$(nproc --all)

    - name: Set up environment variables
      run: |
        cd ${{ github.workspace }}
        source build/envsetup.sh

    - name: Configure Build for Device
      run: |
        cd ${{ env.DEVICE_TREE }}
        lunch lineage_RE879EL1-userdebug

    - name: Build Recovery Image
      run: |
        cd ${{ env.DEVICE_TREE }}
        make bootimage

    - name: Publish Recovery Image as Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ env.DEVICE_TREE }}/out/target/product/RE879EL1/boot.img
        asset_name: lineage-${{ github.event.inputs.branch }}-RE879EL1-recovery.img
        asset_content_type: application/octet-stream
        token: ${{ secrets.GITHUB_TOKEN }}
